"""empty message

Revision ID: 19cab846c82a
Revises: 7b9409dac931
Create Date: 2024-05-09 01:43:19.161425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19cab846c82a'
down_revision = '7b9409dac931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('fk_creator_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_creator_id', 'User', ['creator_id'], ['id'])
        batch_op.drop_column('creator')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint('fk_creator_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_creator_id', 'User', ['creator'], ['id'])
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
