"""family details

Revision ID: 368f476eb5a1
Revises: f1ec54ff1498
Create Date: 2024-05-15 11:31:30.049426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368f476eb5a1'
down_revision = 'f1ec54ff1498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=125), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=125), nullable=True))
        batch_op.add_column(sa.Column('lga', sa.String(length=125), nullable=True))
        batch_op.add_column(sa.Column('community', sa.String(length=125), nullable=True))
        batch_op.create_index(batch_op.f('ix_Family_community'), ['community'], unique=False)
        batch_op.create_index(batch_op.f('ix_Family_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_Family_lga'), ['lga'], unique=False)
        batch_op.create_index(batch_op.f('ix_Family_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Family', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Family_state'))
        batch_op.drop_index(batch_op.f('ix_Family_lga'))
        batch_op.drop_index(batch_op.f('ix_Family_country'))
        batch_op.drop_index(batch_op.f('ix_Family_community'))
        batch_op.drop_column('community')
        batch_op.drop_column('lga')
        batch_op.drop_column('state')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
