"""family city

Revision ID: 6443858ced45
Revises: 368f476eb5a1
Create Date: 2024-05-15 17:09:44.273132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6443858ced45'
down_revision = '368f476eb5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=125), nullable=True))
        batch_op.create_index(batch_op.f('ix_Family_city'), ['city'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Family', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Family_city'))
        batch_op.drop_column('city')

    # ### end Alembic commands ###
