"""renewed migrations

Revision ID: 79fe64e79801
Revises: 
Create Date: 2024-05-17 19:44:53.676137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79fe64e79801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('height', sa.String(length=60), nullable=True),
    sa.Column('hobbies', sa.String(length=120), nullable=True),
    sa.Column('marital_status', sa.Boolean(), nullable=True),
    sa.Column('ethnicity', sa.String(length=120), nullable=True),
    sa.Column('race', sa.String(length=120), nullable=True),
    sa.Column('state_of_origin', sa.String(length=120), nullable=True),
    sa.Column('nationality', sa.String(length=120), nullable=True),
    sa.Column('occupation', sa.String(length=120), nullable=True),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('genotype', sa.String(length=120), nullable=True),
    sa.Column('blood_group', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('skin_color', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Family',
    sa.Column('name', sa.String(length=125), nullable=False),
    sa.Column('country', sa.String(length=125), nullable=True),
    sa.Column('state', sa.String(length=125), nullable=True),
    sa.Column('city', sa.String(length=125), nullable=True),
    sa.Column('lga', sa.String(length=125), nullable=True),
    sa.Column('community', sa.String(length=125), nullable=True),
    sa.Column('creator_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['User.id'], name='fk_creator_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Family', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Family_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_Family_community'), ['community'], unique=False)
        batch_op.create_index(batch_op.f('ix_Family_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_Family_lga'), ['lga'], unique=False)
        batch_op.create_index(batch_op.f('ix_Family_state'), ['state'], unique=False)

    op.create_table('Member',
    sa.Column('registered', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('height', sa.String(length=60), nullable=True),
    sa.Column('hobbies', sa.String(length=120), nullable=True),
    sa.Column('marital_status', sa.Boolean(), nullable=True),
    sa.Column('ethnicity', sa.String(length=120), nullable=True),
    sa.Column('race', sa.String(length=120), nullable=True),
    sa.Column('state_of_origin', sa.String(length=120), nullable=True),
    sa.Column('nationality', sa.String(length=120), nullable=True),
    sa.Column('occupation', sa.String(length=120), nullable=True),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('genotype', sa.String(length=120), nullable=True),
    sa.Column('blood_group', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('skin_color', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_member',
    sa.Column('family_id', sa.String(length=255), nullable=False),
    sa.Column('member_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['Family.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['Member.id'], ),
    sa.PrimaryKeyConstraint('family_id', 'member_id', 'id')
    )
    op.create_table('media',
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('family_id', sa.String(length=255), nullable=True),
    sa.Column('member_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['Family.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['Member.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    op.drop_table('family_member')
    op.drop_table('Member')
    with op.batch_alter_table('Family', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Family_state'))
        batch_op.drop_index(batch_op.f('ix_Family_lga'))
        batch_op.drop_index(batch_op.f('ix_Family_country'))
        batch_op.drop_index(batch_op.f('ix_Family_community'))
        batch_op.drop_index(batch_op.f('ix_Family_city'))

    op.drop_table('Family')
    op.drop_table('User')
    # ### end Alembic commands ###
