"""creator

Revision ID: b51a4b661ca7
Revises: e529a984d1fa
Create Date: 2024-05-08 20:31:53.931672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51a4b661ca7'
down_revision = 'e529a984d1fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator', sa.String(length=255), nullable=False))
        batch_op.create_foreign_key('fk_creator_id', 'User', ['creator'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Family', schema=None) as batch_op:
        batch_op.drop_constraint('fk_creator_id', type_='foreignkey')
        batch_op.drop_column('creator')

    # ### end Alembic commands ###
