"""empty message

Revision ID: f1ec54ff1498
Revises: 19cab846c82a
Create Date: 2024-05-09 23:32:45.678006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ec54ff1498'
down_revision = '19cab846c82a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=255), nullable=True))

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('img')

    with op.batch_alter_table('Member', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
